config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books,only:[:new, :create, :index, :show, :edit, :destroy, :update]
  resources :users,only:[:index, :show, :edit, :update]

  patch 'books/:id' => 'books#update', as: 'update_book'
  get "/home/about" => "homes#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ##アプリ14章
  has_one_attached :profile_image

   validates :name, uniqueness: true
   validates :name, length: { in: 2..20 }
   validates :introduction, length: { maximum: 50 }


  has_many :books, dependent: :destroy

  # def get_image
  #   if image.attached?
  #     image
  #   else
  #     'no_image.jpg'
  #   end
  # end

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image
      # profile_image.variant(resize: "63x63").processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @newbook = Book.new
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
    redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
    render :edit
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
  def index
   @users = User.all
   @user = current_user
   @book = Book.new
  end


  def show
   @book = Book.new
   @newbook = Book.new
   @users = User.all
   @books = Book.all
   @user = User.find(params[:id])
  end

  def edit
   @user = User.find(params[:id])
   if @user == current_user
   render :edit
   else
   redirect_to user_path(current_user)
   end
  end

  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
   redirect_to user_path, notice: 'You have updated user successfully.'
   else
   render :edit
   end
  end

  private

  def user_params
   params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h2>
<% if @book.errors.any? %>
     <%= @book.errors.count %>error prohibited this obj from being saved:
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
<% end %>

<%= form_with model:@book,url: update_book_path(@book.id), method: :patch, local:true do |f| %>
<div class="form-group">
      <label for="book_title">Title</label></br>
      <%= f.text_field :title %>
     </div>

     <div class="form-group">
      <label for="book_opnion">Opnion</label></br>
      <%= f.text_area :body %>
     </div>

     <div class="form-group">
      <%= f.submit 'Update Book', class:"btn btn-success" %>
     </div>


     <div class=link>
      <%= link_to "Show", book_path %> | <%= link_to "Back", books_path %>
     </div>

</div>
<% end %>

</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%=form_with model:Book.new, local:true do |f| %>

    <% if @book.errors.any? %>
     <%= @book.errors.count %>error prohibited this obj from being saved:
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

    <h2>User info</h2>



    <table class="table">
     <tbody>
      <tr>
       <th>
        <%= image_tag @user.get_profile_image("63x63") %>
       </th>
      </tr>
      <tr>
       <th>name</th>
       <th><%= @user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= @user.introduction %></th>
      </tr>
     </tbody>
    </table>

    <div class="row">
     <!--< if @user.id == current_user.id %>-->
      <%= link_to edit_user_path(current_user), class:'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </div>


    <h2>New book</h2>


     <div class="form-group">
      <label for="book_title">Title</label></br>
      <%= f.text_field :title %>
     </div>

     <div class="form-group">
      <label for="book_opnion">Opnion</label></br>
      <%= f.text_area :body %>
     </div>
     <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
     </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opnion</th>
        </tr>
       </thead>
      <tbody>
      <% @books.each do |book| %>
        <tr>
          <th>
           <%= link_to user_path(book.user) do %>
           <%= image_tag book.user.get_profile_image("40x40") %>
           <% end %>
           </th>
          <th><%= link_to book.title, book_path(book) %></th>
          <th><%= book.body %></th>
        </tr>
      <% end %>
      </tbody>
      </table>

    </div>
    <% end %>

  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <% if @book.errors.any? %>
     <%= @book.errors.count %>error prohibited this obj from being saved:
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

    <h2>User info</h2>

    <%= image_tag @book.user.get_profile_image("63x63") %>

    <table class="table">
     <tbody>
      <tr></tr>
      <tr>
       <th>name</th>
       <th><%= @book.user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= @book.user.introduction %></th>
      </tr>
     </tbody>
    </table>

    <div class="row">

      <%= link_to edit_user_path(@user), class:'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
      <% end %>

    </div>


    <h2>New book</h2>
    <%=form_with model:Book.new, local:true do |f| %>

     <div class="form-group">
      <label for="book_title">Title</label></br>
      <%= f.text_field :title %>
     </div>

     <div class="form-group">
      <label for="book_opnion">Opnion</label></br>
      <%= f.text_area :body %>
     </div>
     <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
     </div>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>


    <table class="table">
     <tbody>
      <tr>
       <td>
        <%= link_to user_path(@book.user)  do %>
         <%= image_tag @book.user.get_profile_image("40x40") %></br>
         <%= @book.user.name %>
        <% end %>
       </td>
       <td><%= link_to @book.title, book_path(@book) %></td>
       <td><%= @book.body %></td>
       <% if @book.user == current_user %>
       <td>
        <%= link_to"Edit", edit_book_path(@book), class: 'btn btn-success btn-sm btn-blok sign_up' %>
       </td>
       <td>
        <%= link_to"Destroy", book_path, class: 'btn btn-danger btn-sm', method: :delete,"data-confirm" => "本当に消しますか？" %>
       </td>
       <% end %>
      </tr>
     </tbody>
    </table>


    </div>
    <% end %>
  </div>
</div>

app/views/homes/about.html.erb
<main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to
            <i class="fas fa-book"></i><strong>Bookers</strong>!
            </h1>


          </div>
        </div>
      </div>
    </main>

app/views/homes/top.html.erb
<main>
      <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>welcome to
            <i class="fas fa-book"></i>
            <strong>Bookers</strong>
              !!
            </h1>
            <p>
               In
            <i class="fas fa-book"></i>
            <strong>Bookers</strong>
             ,
            </p>
            <p>you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>

            <div class="btn-wrapper col-10 mx-auto">
             <div class="row">
                <%= link_to"Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
             </div>
             <div class="row">
                <%= link_to"Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
             </div>
            </div>

          </div>
        </div>
      </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">-->
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!--<= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <% if flash[:notice] %>
            <div class="flash">
            <%= flash[:notice] %>
            </div>
            <% end %>


            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
               <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
               <i class="fas fa-home"></i>Home
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to users_path, class: 'nav-link text-light' do %>
               <i class="fas fa-users"></i>Users
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to books_path, class: 'nav-link text-light' do %>
               <i class="fas fa-book-open"></i>Books
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
               <i class="fas fa-sign-out-alt"></i>Log out
               <% end %>
              </li>
            <% else %>
              <li class="nav-item">
               <%= link_to root_path, class: 'nav-link text-light' do %>
               <i class="fas fa-home"></i>Home
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to about_path, class: 'nav-link text-light' do %>
               <i class="fas fa-link"></i>About
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
               <i class="fas fa-user-plus"></i>Sign up
               <% end %>
              </li>
              <li class="nav-item">
               <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
               <i class="fas fa-sign-in-alt"></i>Log in
               <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_list.html.erb
    <% if book.errors.any? %>
     <%= book.errors.count %>件のエラーが発生しました
     <ul>
      <% book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    <% end %>

    <h2>User info</h2>

    <%= image_tag user.get_profile_image("63x63") %>

    <table class="table">
     <tbody>
      <tr></tr>
      <tr>
       <th>name</th>
       <th><%= user.name %></th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
     </tbody>
    </table>

    <div class="row">

      <%= link_to edit_user_path(user), class:'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
      <% end %>

    </div>


    <h2>New book</h2>
    <%=form_with model:book, local:true do |f| %>

     <div class="form-group">
      <label for="book_title">Title</label></br>
      <%= f.text_field :title %>
     </div>

     <div class="form-group">
      <label for="book_opnion">Opinion</label></br>
      <%= f.text_area :body %>
     </div>




     <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
     </div>
    <% end %>

app/views/users/edit.html.erb
<div class="container">
　<div class="row">
　　<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

　　<h2>User info</h2>

　　<% if @user.errors.any? %>
     <%= @user.errors.count %>error prohibited this obj from being saved:
     <ul>
      <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
　　<% end %>

　　<%= form_with model: @user, local:true do |f| %>
　　 <div class="form-group">
  　　<label for="inputName">Name</label>
  　   <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" ,class:"form-control name"%>
  　 </div>
  　 <div class="form-group">
  　　<label for="inputImage">Image</label>
  　   <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  　 </div>
  　 <div class="form-group">
  　　<label for="inputIntroduction">Introduction</label>
  　   <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介" ,class:"form-control introduction"%>
  　 </div>
  　 <div class="form-group">
  　   <%= f.submit "Update User", class:"btn btn-secondary"%>
  　 </div>
　　<% end %>


　　</div>
　</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= render 'list', book: @book, user: @user %>
   </div>


    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
       </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <th><%= image_tag user.get_profile_image("50x50") %></th>
          <th><%= user.name %></th>
          <th><%= link_to"Show", user_path(user) %></th>
        </tr>
      <% end %>

      </tbody>
      </table>

    </div>


  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= render 'list', book: @book, user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opnion</th>
        </tr>
       </thead>
       <tbody>
        <% @books.each do |book| %>
         <% if book.user == @user %>
        <tr>
          <td>
            <%= link_to user_path(@user)  do %>
            <%= image_tag book.user.get_profile_image("40x40") %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
         <% end %>
        <% end %>
        </tbody>
       </table>

    </div>
  </div>
</div>